update readme--> added contribution guidelines
destrex271/pgweb-testing-harness pull request #25
Opened 2023-12-23 16:08 UTC by pinak22dhir

made changes in readme

2023-12-23 16:09 UTC, pinak22dhir commented
@destrex271 , resolved issue #24

2023-12-23 16:45 UTC, destrex271 commented on README.md
Please fix the cases for Headings.

2023-12-23 16:45 UTC, destrex271 commented on README.md
The formatting is not good tbh, please take a look at the entire pr once again. Also the code of conduct feels out of place.

2023-12-23 16:45 UTC, destrex271 commented on README.md
Contribution Guidelines should be specific to the project. Please try to run the project locally and understand the current workflow to write them. They do not need to be lengthy or similar to some other source

2023-12-23 16:52 UTC, pinak22dhir commented on README.md
let me see @destrex271

2023-12-25 08:27 UTC, destrex271 requested changes

2023-12-25 08:27 UTC, destrex271 commented on README.md
![image](https://github.com/destrex271/pgweb-testing-harness/assets/59926121/55bda52f-bdcf-4002-8834-fa564a61d0c8)
Again the formatting is a little messed up.

![image](https://github.com/destrex271/pgweb-testing-harness/assets/59926121/26cd420e-2a34-44d8-854b-ec229e1feb15)
Also we already have a contributing section in our readme and the content that you have submitted is not what we want to convey.

Hint: Please don't be in a hurry to submit anything in your pull request, otherwise we'll have to take it down. Review your changes once in your local markdown preview.

2024-01-05 13:41 UTC, destrex271 commented
Closing due to inactivity

2024-01-05 13:41 UTC, closed without merging